version: '3'
services:  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_with_datadog
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # Porta de acesso padrão do RabbitMQ
      - "15672:15672"  # Porta do painel de controle do RabbitMQ
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq  # Volume para persistir os dados do RabbitMQ
